version: "3.9"
services:
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/services/web/Dockerfile
    volumes:
      - ./logs:/home/appuser/logs
      - ./prometheus:/home/appuser/prometheus
    command: gunicorn --log-level debug --timeout 300 --bind 0.0.0.0:3000 --worker-class=uvicorn.workers.UvicornWorker --workers=2 app:app
    expose:
      - "3000"
    restart: unless-stopped
  cron:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/services/web/Dockerfile
    volumes:
      - ./logs:/home/appuser/logs
      - ./prometheus:/home/appuser/prometheus
    command: python cron_runner.py
    expose:
      - "3000"
    restart: unless-stopped
  nginx:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/services/nginx/Dockerfile
    volumes:
      - ./shared:/usr/share
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - web

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - ./docker/services/promtail/config.yml:/etc/promtail/config.yml
      - ./logs:/var/log
    command: -config.file=/etc/promtail/config.yml -config.expand-env
    restart: unless-stopped
    environment:
      - HOST_HOSTNAME=${HOSTNAME}
