services:
  database3:
    image: "postgres:15"
    container_name: "points_postgres"
    environment:
      - POSTGRES_DB=points
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres_points_data:/var/lib/postgresql/data
volumes:
  postgres_points_data:
