"""Add quest_event table

Revision ID: 000000000003
Revises: 000000000002
Create Date: 2024-05-06 13:50:20.505797

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '000000000003'
down_revision = '000000000002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table(
        'quest_event',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_profile_id', sa.UUID(), nullable=False),
        sa.Column('event_name', sa.String(), nullable=False),
        sa.Column('event_description', sa.String(), nullable=True),
        sa.Column('points', sa.Integer(), nullable=False),
        sa.Column('logs', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_table('quest_event')
    # ### end Alembic commands ###
