"""Adds signature field to QuestEvent

Revision ID: 000000000007
Revises: 000000000006
Create Date: 2024-05-10 13:30:20.901184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000007'
down_revision = '000000000006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest_event', sa.Column('signature', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'quest_event', ['signature'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quest_event', type_='unique')
    op.drop_column('quest_event', 'signature')
    # ### end Alembic commands ###
