"""Add user_profile table optional wallet_address column

Revision ID: 000000000002
Revises: 000000000001
Create Date: 2024-05-06 13:24:22.702062

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '000000000002'
down_revision = '000000000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column('user_profile', sa.Column('wallet_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column('user_profile', 'wallet_address')
    # ### end Alembic commands ###
