"""Add a basic user_token table to save user X bearer tokens

Revision ID: 000000000007
Revises: 000000000006
Create Date: 2024-05-10 14:55:14.170678

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '000000000007'
down_revision = '000000000006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table(
        'user_token',
        sa.Column('user_profile_id', sa.UUID(), nullable=False),
        sa.Column('access_token', sa.String(), nullable=False),
        sa.Column('refresh_token', sa.String(), nullable=False),
        sa.Column('expires_at', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ),
        sa.PrimaryKeyConstraint('user_profile_id'),
        sa.UniqueConstraint('user_profile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_table('user_token')
    # ### end Alembic commands ###
