"""Add a basic user_token table to save user bearer tokens

Revision ID: 000000000009
Revises: 000000000008
Create Date: 2024-05-13 10:52:37.993088

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '000000000009'
down_revision = '000000000008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table(
        'user_token',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_profile_id', sa.UUID(), nullable=False),
        sa.Column('token_issuer', sa.String(), nullable=False),
        sa.Column('access_token', sa.String(), nullable=False),
        sa.Column('refresh_token', sa.String(), nullable=False),
        sa.Column('expires_at', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_profile_id', 'token_issuer', name='_user_issuer_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_table('user_token')
    # ### end Alembic commands ###
