"""Adds leaderboard

Revision ID: 000000000005
Revises: 000000000004
Create Date: 2024-05-08 15:42:00.502260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000005'
down_revision = '000000000004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard',
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('user_profile_id')
    )
    op.create_index(op.f('ix_leaderboard_points'), 'leaderboard', ['points'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_points'), table_name='leaderboard')
    op.drop_table('leaderboard')
    # ### end Alembic commands ###
