"""Adds Discord username and ID

Revision ID: 000000000007
Revises: 000000000006
Create Date: 2024-05-10 10:18:57.871730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000007'
down_revision = '000000000006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('discord_id', sa.String(), nullable=True))
    op.add_column('user_profile', sa.Column('discord_username', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user_profile', ['discord_username'])
    op.create_unique_constraint(None, 'user_profile', ['discord_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_column('user_profile', 'discord_username')
    op.drop_column('user_profile', 'discord_id')
    # ### end Alembic commands ###
