"""Change user_profile table email to x_id

Revision ID: 000000000005
Revises: 000000000004
Create Date: 2024-05-08 15:54:38.083897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000005'
down_revision = '000000000004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column('user_profile', sa.Column('x_id', sa.String(), nullable=False))
    op.drop_constraint('user_profile_email_key', 'user_profile', type_='unique')
    op.drop_constraint('user_profile_x_username_key', 'user_profile', type_='unique')
    op.create_unique_constraint(None, 'user_profile', ['x_id'])
    op.drop_column('user_profile', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column('user_profile', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_profile_x_username_key', 'user_profile', ['x_username'])
    op.create_unique_constraint('user_profile_email_key', 'user_profile', ['email'])
    op.drop_column('user_profile', 'x_id')
    # ### end Alembic commands ###
