"""Makes QuestEvent signature unique only if not null or empty

Revision ID: 000000000010
Revises: 000000000009
Create Date: 2024-05-13 14:40:01.020808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000010'
down_revision = '000000000009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quest_event_signature_key', 'quest_event', type_='unique')
    op.create_index('idx_unique_signature', 'quest_event', ['signature'], unique=True, postgresql_where=sa.text("signature IS NOT NULL AND signature != ''"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unique_signature', table_name='quest_event', postgresql_where=sa.text("signature IS NOT NULL AND signature != ''"))
    op.create_unique_constraint('quest_event_signature_key', 'quest_event', ['signature'])
    # ### end Alembic commands ###
