"""Makes QuestEvent event_name of type enum

Revision ID: 000000000008
Revises: 000000000007
Create Date: 2024-05-10 15:02:39.503760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '000000000008'
down_revision = '000000000007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quest_event', 'event_name')
    event_name_enum = sa.Enum('connect_wallet', 'used_faucet', 'make_tx', 'deploy_contract', 'join_discord', 'follow_galardiel_on_x', 'manual', name='event_name_enum')
    event_name_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('quest_event', sa.Column('event_name', event_name_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quest_event', 'event_name')
    op.add_column('quest_event', sa.Column('event_name', sa.String(), nullable=False))
    sa.Enum(name='event_name_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
