"""Add profile_picture_url and cached_profile_picture_url columns to user_profile table

Revision ID: 000000000011
Revises: 000000000010
Create Date: 2024-05-13 13:20:13.279178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000011'
down_revision = '000000000010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column('user_profile', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.add_column('user_profile', sa.Column('cached_profile_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column('user_profile', 'cached_profile_image_url')
    op.drop_column('user_profile', 'profile_image_url')
    # ### end Alembic commands ###
